Controllers/MessagesController.cs
using SocialNetwork.DatabaseContent;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SocialNetwork.Controllers
{
    public class MessagesController : Controller
    {
        socialNetworkEntities db = new socialNetworkEntities();
        // GET: Messages
        public ActionResult Index()
        {
            if (Session["currentUserID"] == null || Convert.ToInt32(Session["currentUserID"]) == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            int current_user = Convert.ToInt32(Session["currentUserID"]);
            //var all_friends = db.Friends.Where(x => x.friendOfID == current_user || x.userID == current_user).ToList();   SIR
            //var all_friends = db.Users.ToList();  myyself after sir
            List<User> all_friends = db.Users.Where(x => x.userID != current_user).ToList(); //        MYSELF
            //List<Message> all_friends = db.Messages.ToList(); 
            return View(all_friends);
        }

        public JsonResult SendMessage(Message Message)
        {
            try
            {
                Message.fromUserID = Convert.ToInt32(Session["currentUserID"]);
                //Message.toUserID = Convert.ToInt32(Session["id"]);        MYSELF
                db.Messages.Add(Message);
                db.SaveChanges();
            }
            catch (Exception ex)
            {
                return Json(new { Status = false, msg = ex.Message });
            }
            //save to message table
            return Json(new { Status = true, msg = "Message Sent Successfully" });
        }
        public ActionResult toGEtId(int name)
        {
            Session["id"] = name;
            //return RedirectToAction("Index");
            return View("Index");
        }
        public PartialViewResult ChatHistory(int? userID)
        {
            ViewBag.userID = userID;
            int currentUserID = Convert.ToInt32(Session["currentUserID"]);
            var old_data = db.Messages.Where(x => (x.fromUserID == currentUserID && x.toUserID == userID) || (x.fromUserID == userID && x.toUserID == currentUserID));
            return PartialView(old_data.ToList());
        }

        public ActionResult readID(int id)
        {
            //var data = db.Friends.Where(x => x.friendID == id).ToList();  SIR
            var dataID = db.Users.Where(x => x.userID == id).ToList();
            return View("Index", dataID);
        }
    }
}

Views/Messages/ChatHistory.cshtml
@model List<SocialNetwork.DatabaseContent.Message>

<div id="ChatHistory" data-url="@Url.Action("ChatHistory",null, new { userID=ViewBag.userID  })">
    @if (Model != null)
     {
        <div class="peoples-mesg-box">
            <p>@Session["id"]</p>
            <div class="conversation-head">
                @*<figure><img src="~/Content/socialMedia/images/resources/friend-avatar.jpg" alt=""></figure>
                <span><i>online</i></span>*@

            </div>
            @*<div id="chattingContainer">*@
                <ul class="chatting-area">
                    
                    @foreach (var data in Model)
                    {
                        //if (data.fromUserID == Convert.ToInt32(Session["currentUserID"]) && data.toUserID == Convert.ToInt32(Session["id"]))
                        //{
                        //var myName = data.User.userUserName;
                        //if (data.toUserID != Convert.ToInt32(Session["currentUserID"]))
                        if (data.toUserID != Convert.ToInt32(Session["currentUserID"]))
                        //if (int.TryParse(data.toUserID, out var toUserID) != Session["currentUserID"]){ }
                        {
                            <li class="me">
                                <figure><img src="@(data.User.userPhoto != null ? Url.Content(data.User.userPhoto):"")" alt=""></figure>
                                @*<p>what's liz short for? :)</p>*@
                                <p>@Html.DisplayFor(model => data.currentUserMessage)</p>
                            </li>
                            }
                            else
                            {
                            <li class="you">
                                @*<figure><img src="~/Content/socialMedia/images/resources/userlist-1.jpg" alt=""></figure>*@
                                <figure><img src="@(data.User.userPhoto != null ? Url.Content(data.User.userPhoto):"")" alt=""></figure>
                                @*<p>Elizabeth lol</p>*@
                                <p>@Html.DisplayFor(model => data.currentUserMessage)</p>
                                @*<p>@Html.DisplayFor(model => data.fromUserID)</p>*@
                            </li>
                            }
                            //}
                        }
                </ul>
                <div class="message-text-container">
                    @using (Html.BeginForm("SendMessage", "Messages", FormMethod.Post, new { @class = "ajaxSubmit", @data_callback = "RefreshChat" }))
                    {
                        <input type="hidden" name="toUserID" value="@ViewBag.userID" />
                        <textarea name="currentUserMessage"></textarea>
                        <button type="submit" title="send"><i class="fa fa-paper-plane"></i></button>
                    }
                </div>
            @*</div>*@
        </div>
     }
</div>
<!--<script>-->
    @*function checkUser(fromUserID, toUserID) {
        if (@Session["currentUserID"]== Messages.fromUserID && selectedUserID == Messages.toUserID) {
            document.getElementById("chattingContainer").style.visibility = show;
        }
        else {
            document.getElementById("chattingContainer").style.visibility = none;
        }
    }*@
<!--</script>-->

Views/Messages/Index.cshtml
@*@model List<SocialNetwork.DatabaseContent.Friend>*@
@model List<SocialNetwork.DatabaseContent.User>
<!--Messages-->
@{
    ViewBag.Title = "Index";


}
<style>
    .message-box > .chattingPerson {
        float: right
    }

    .chattingPerson > h4 {
        color: blue;
    }
</style>

<div class="col-lg-6" style="margin:auto">
    <div class="central-meta">
        <div class="messages">
            <h5 class="f-title"><i class="ti-bell"></i>All Users @*<span class="more-options"><i class="fa fa-ellipsis-h"></i>@*</span>*@</h5>
            <div class="message-box">
                <ul class="peoples">
                    @foreach (var data in Model)
                    {
                        <li>
                            <a class="ViewMessage" data-url="@Url.Action("ChatHistory", new { userID = data.userID })">
                                @*<a class="ViewMessage" data-url="@Url.Action("ChatHistory", new { userID = data.userID })">*@
                                @*<a class="ViewMessage" data-url="@Url.Action("ChatHistory", new { userID = Session["id"] })">*@
                                <figure>
                                    @*<a href="@Url.Action("readID", new {id=data.friendID})"><img src="@(data.User.userPhoto != null ? Url.Content(data.Users.userPhoto):"")" alt="" )</a>*@
                                    <img src="@(data.userPhoto != null ? Url.Content(data.userPhoto):"")" alt="" ) />
                                    @*<span class="status f-online"></span>*@
                                </figure>
                                <div class="people-name">
                                    <span>@(data.userFirstName) @(data.userLastName)</span>
                                    @*<a href="@Url.Action("toGEtId", new {name=data.userID})"><span id="getUserName" onclick="getUserName((this.textContent || this.innerTEXT),@data.userID)">@(data.userFirstName) @(data.userLastName)</span></a>*@
                                    @*<span id="getUserName" onclick="getUserName((this.textContent || this.innerTEXT),@data.userID)">*@@*<a href="@Url.Action("readID", new {id=data.userID})">*@@*<span>@(data.userFirstName) @(data.userLastName)</span>*@@*</a>*@@*@(data.userFirstName) @(data.userLastName)*@@*<label id="getUserID" value="@data.userID">@(data.userID)</label>*@@*</span>*@
                                </div>
                            </a>
                        </li>
                    }
                    @*<li>
                            <figure>
                                <img src="~/Content/socialMedia/images/resources/friend-avatar3.jpg" alt="">
                                <span class="status f-away"></span>
                            </figure>
                            <div class="people-name">
                                <span>Andrew</span>
                            </div>
                        </li>
                        <li>

                            <figure>
                                <img src="~/Content/socialMedia/images/resources/friend-avatar.jpg" alt="">
                                <span class="status f-online"></span>
                            </figure>

                            <div class="people-name">
                                <span>jason bourne</span>
                            </div>
                        </li>
                        <li>

                            <figure>
                                <img src="~/Content/socialMedia/images/resources/friend-avatar4.jpg" alt="">
                                <span class="status off-online"></span>
                            </figure>
                            <div class="people-name">
                                <span>Sarah Grey</span>
                            </div>
                        </li>
                        <li>

                            <figure>
                                <img src="~/Content/socialMedia/images/resources/friend-avatar5.jpg" alt="">
                                <span class="status f-online"></span>
                            </figure>
                            <div class="people-name">
                                <span>bill doe</span>
                            </div>
                        </li>
                        <li>

                            <figure>
                                <img src="~/Content/socialMedia/images/resources/friend-avatar6.jpg" alt="">
                                <span class="status f-away"></span>
                            </figure>
                            <div class="people-name">
                                <span>shen cornery</span>
                            </div>
                        </li>
                        <li>

                            <figure>
                                <img src="~/Content/socialMedia/images/resources/friend-avatar7.jpg" alt="">
                                <span class="status off-online"></span>
                            </figure>
                            <div class="people-name">
                                <span>kill bill</span>
                            </div>
                        </li>
                        <li>

                            <figure>
                                <img src="~/Content/socialMedia/images/resources/friend-avatar8.jpg" alt="">
                                <span class="status f-online"></span>
                            </figure>
                            <div class="people-name">
                                <span>jasmin walia</span>
                            </div>
                        </li>
                        <li>

                            <figure>
                                <img src="~/Content/socialMedia/images/resources/friend-avatar6.jpg" alt="">
                                <span class="status f-online"></span>
                            </figure>
                            <div class="people-name">
                                <span>neclos cage</span>
                            </div>
                        </li>*@
                </ul>
                @*<div class="chattingPerson">
                    <h5>You are chatting with</h5>
                    <h4 id="print"></h4>
                    <h4 id="print1"></h4>
                </div>*@
                <div class="message-text-container">
                    @{Html.RenderAction("ChatHistory", new { userID = Model.FirstOrDefault()?.userID });}
                    @*@{Html.RenderAction("ChatHistory", new { userID = Model.FirstOrDefault()?.userID });}*@
                    @*@{Html.RenderAction("ChatHistory", new { userID = Session["id"] });}*@
                    @*@Html.Partial("ChatHistory", Model.FirstOrDefault()?.)*@
                </div>
            </div>
        </div>
    </div>
</div><!-- centerl meta -->


<script src="~/Scripts/jquery-3.4.1.min.js"></script>

<script>
    $(document).on('click', ".ViewMessage", function () {
        $("#ChatHistory").load($(this).data("url"));
    });
</script>
<script>
    function getUserName(userNName, ui) {
        document.getElementById("print").innerHTML = userNName;
        var uID = ui;
        /*var uID = document.getElementById("getUserID").value;*/
        document.getElementById("print1").innerHTML = uID;
    }
</script>