Controllers/SignUpController.cs
using SocialNetwork.DatabaseContent;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SocialNetwork.Controllers
{
    public class SignUpController : Controller
    {
        socialNetworkEntities db = new socialNetworkEntities();
        // GET: SignUp
        public ActionResult Index()
        {
            List<User> all_data = db.Users.ToList();
            return View(all_data);
        }

        public ActionResult AddUser(string userFirstName, string userLastName, string userUserName, string userPassword, string userDOB, int userPhone, string userEmail, string userGender, string userCity, string userState, string userCountry, HttpPostedFileBase selectedImg, User userImg1)
        {
            //string file_name = System.IO.Path.GetFileName(selectedImg.FileName);
            //string new_path = Server.MapPath("~/Uploads/" + file_name);
            string path = Server.MapPath("~/Uploads");
            string file_name = selectedImg.FileName;
            string new_path = path + "/" + file_name;
            //if (Directory.Exists(path))
            //{
            //    Directory.CreateDirectory(path);
            //}
            selectedImg.SaveAs(new_path);

            userImg1.userPhoto = "~/Uploads/" + file_name;
            User value = new User();
            value.userPhoto = userImg1.userPhoto;
            value.userFirstName = userFirstName;
            value.userLastName = userLastName;
            value.userUserName = userUserName;
            value.userPassword = userPassword;
            value.userEmail = userEmail;
            value.userDOB = userDOB;
            value.userGender = userGender;
            value.userPhone = userPhone;
            value.userCity = userCity;
            value.userState = userState;
            value.userCountry = userCountry;
            Session["currentUserName"] = userUserName;
            db.Users.Add(value);
            //db.Users.Add(userImg);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");

        }
    }
}

Views/SignUp/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = null;
}
<link rel="icon" href="~/Content/socialMedia/images/fav.png" type="image/png" sizes="16x16">

<link rel="stylesheet" href="~/Content/socialMedia/css/main.min.css">
<link rel="stylesheet" href="~/Content/socialMedia/css/style.css">
<link rel="stylesheet" href="~/Content/socialMedia/css/color.css">
<link rel="stylesheet" href="~/Content/socialMedia/css/responsive.css">
<style>

    .registerForm {
        padding-left: 400px;
        width: 70%;
    }
    .log-title{
        color:#1D306D;
    }
</style>

@using (Html.BeginForm("AddUser", "SignUp", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="registerForm">
        <h2 class="log-title">Register to Chatbook</h2>
        <div class="form-group">
            <input type="text" required="required" id="userFirstName" name="userFirstName"/>
            <label class="control-label" for="input">First Name</label><i class="mtrl-select"></i>
        </div>
        <div class="form-group">
            <input type="text" required="required" id="userLastName" name="userLastName"/>
            <label class="control-label" for="input">Last Name</label><i class="mtrl-select"></i>
        </div>
        <div class="form-group">
            <input type="text" required="required" id="userUserName" name="userUserName"/>
            <label class="control-label" for="input">User Name</label><i class="mtrl-select"></i>
        </div>
        <div class="form-group">
            <input type="password" required="required" id="userPassword" name="userPassword"/>
            <label class="control-label" for="input">Password</label><i class="mtrl-select"></i>
        </div>
        <div class="form-radio">
            <div class="radio">
                <label>
                    <input type="radio" name="userGender" checked="checked" id="userGender" value="Male"/><i class="check-box"></i>Male
                </label>
            </div>
            <div class="radio">
                <label>
                    <input type="radio" name="userGender" id="userGender" value="Female"/><i class="check-box"></i>Female
                </label>
            </div>
            <div class="radio">
                <label>
                    <input type="radio" name="userGender" id="userGender" value="Other"/><i class="check-box"></i>Other
                </label>
            </div>
        </div>
        <div class="form-group">
            <input type="text" required="required" id="userEmail" name="userEmail"/>
            <label class="control-label" for="input"><a href="https://wpkixx.com/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="6c29010d05002c">[email&#160;protected]</a></label><i class="mtrl-select"></i>
        </div>
        <div class="form-group">
            <input type="text" required="required" id="userPhone" name="userPhone"/>
            <label class="control-label" for="input">Mobile Number</label><i class="mtrl-select"></i>
        </div>
        <div class="form-group">
            <input type="text" required="required" id="userDOB" name="userDOB"/>
            <label class="control-label" for="input">Date of Birth</label><i class="mtrl-select"></i>
        </div>
        <div class="form-group">
            <input type="text" required="required" id="userCity" name="userCity"/>
            <label class="control-label" for="input">City</label><i class="mtrl-select"></i>
        </div>
        <div class="form-group">
            <input type="text" required="required" id="userState" name="userState"/>
            <label class="control-label" for="input">State</label><i class="mtrl-select"></i>
        </div>
        <div class="form-group">
            <input type="text" required="required" id="userCountry" name="userCountry"/>
            <label class="control-label" for="input">Country</label><i class="mtrl-select"></i>
        </div>
        <div class="form-group">
            <label class="control-label" for="input">Photo</label><i class="mtrl-select"></i><br />
            <input type="file" id="selectedImg" name="selectedImg"/>
        </div>
        <div class="checkbox">
            <label>
                <input type="checkbox" checked="checked" /><i class="check-box"></i>Accept Terms & Conditions ?
            </label>
        </div>
        <a href="@Url.Action("Index", "Login")" title="" class="already-have">Already have an account</a>
        <div class="submit-btns">
            @*<button class="mtr-btn signup" type="button"><span>Register</span></button>*@
            <button value="Submit" name="">Register</button>
        </div>

        @*<button onclick=" return checkEmpty();">Log In</button>*@
    </div>
}